require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/losses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Loss. As you add validations to Loss, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Loss.create! valid_attributes
      get losses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      loss = Loss.create! valid_attributes
      get loss_url(loss)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_loss_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      loss = Loss.create! valid_attributes
      get edit_loss_url(loss)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Loss" do
        expect {
          post losses_url, params: { loss: valid_attributes }
        }.to change(Loss, :count).by(1)
      end

      it "redirects to the created loss" do
        post losses_url, params: { loss: valid_attributes }
        expect(response).to redirect_to(loss_url(Loss.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Loss" do
        expect {
          post losses_url, params: { loss: invalid_attributes }
        }.to change(Loss, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post losses_url, params: { loss: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested loss" do
        loss = Loss.create! valid_attributes
        patch loss_url(loss), params: { loss: new_attributes }
        loss.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the loss" do
        loss = Loss.create! valid_attributes
        patch loss_url(loss), params: { loss: new_attributes }
        loss.reload
        expect(response).to redirect_to(loss_url(loss))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        loss = Loss.create! valid_attributes
        patch loss_url(loss), params: { loss: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested loss" do
      loss = Loss.create! valid_attributes
      expect {
        delete loss_url(loss)
      }.to change(Loss, :count).by(-1)
    end

    it "redirects to the losses list" do
      loss = Loss.create! valid_attributes
      delete loss_url(loss)
      expect(response).to redirect_to(losses_url)
    end
  end
end
