require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tubes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Tube. As you add validations to Tube, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Tube.create! valid_attributes
      get tubes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tube = Tube.create! valid_attributes
      get tube_url(tube)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tube_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tube = Tube.create! valid_attributes
      get edit_tube_url(tube)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tube" do
        expect {
          post tubes_url, params: { tube: valid_attributes }
        }.to change(Tube, :count).by(1)
      end

      it "redirects to the created tube" do
        post tubes_url, params: { tube: valid_attributes }
        expect(response).to redirect_to(tube_url(Tube.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tube" do
        expect {
          post tubes_url, params: { tube: invalid_attributes }
        }.to change(Tube, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post tubes_url, params: { tube: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tube" do
        tube = Tube.create! valid_attributes
        patch tube_url(tube), params: { tube: new_attributes }
        tube.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tube" do
        tube = Tube.create! valid_attributes
        patch tube_url(tube), params: { tube: new_attributes }
        tube.reload
        expect(response).to redirect_to(tube_url(tube))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        tube = Tube.create! valid_attributes
        patch tube_url(tube), params: { tube: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tube" do
      tube = Tube.create! valid_attributes
      expect {
        delete tube_url(tube)
      }.to change(Tube, :count).by(-1)
    end

    it "redirects to the tubes list" do
      tube = Tube.create! valid_attributes
      delete tube_url(tube)
      expect(response).to redirect_to(tubes_url)
    end
  end
end
